### ISSUE TITLE
Upgrading style to new mapbox studio

### ISSUE THREAD

**Issue by erickhun** [mapbox/mapbox-studio-picture-book.tm2#1]
hi @samanpwbb  !

I have 2 questions : 

I would love to use this map with the new mapbox studio. 
Tried to find ressources to migrate those files but didn't find any. Do you have any recommendation? Or is the better way to use the old , and it will still be compatible with the current mapbox API?

I've seen the demo here : https://www.mapbox.com/bites/00099/  can I use it as a template or is there any concern about that ? 

Thank you!

**Comment by dasulit** [comment]
You can use the images in this repo to recreate this style in the current Mapbox Studio. Since we are no longer working on this project, we will be archiving this repo, but assets can still be downloaded. Please [contact support](https://www.mapbox.com/contact/support/) if you have more questions!
